def githubName = binding.variables['GITHUB_NAME']
def displayName = binding.variables['DISPLAY_NAME']

folder('Tools') {
    description('Folder for miscellaneous tools.')
}

job('Tools/clone-repository') {
    description('Clone a Git repository into the workspace.')

    parameters {
        stringParam('GIT_REPOSITORY_URL', '', 'Git URL of the repository to clone')
    }

    wrappers {
        preBuildCleanup()
    }

    steps {
        shell('git clone "$GIT_REPOSITORY_URL" .')
    }
}

job('Tools/SEED') {
    description('Seed job that creates CI jobs from a GitHub repository description.')

    parameters {
        stringParam('GITHUB_NAME', '', 'GitHub repository owner/repo_name (e.g.: EpitechIT31000/chocola)')
        stringParam('DISPLAY_NAME', '', 'Display name for the job')
    }

    wrappers {
        preBuildCleanup()
    }
}

if (githubName && displayName) {
    job(displayName) {
        description("CI job generated by SEED for ${githubName}")

        properties {
            githubProjectUrl("https://github.com/${githubName}")
        }

        scm {
            git {
                remote {
                    url("https://github.com/${githubName}.git")
                    credentials('github-token')
                }
                branches('*/main')
            }
        }

        triggers {
            scm('* * * * *')
        }

        wrappers {
            preBuildCleanup()
        }

        steps {
            shell('make fclean')
            shell('make')
            shell('make tests_run')
            shell('make clean')
        }
    }
}

