def githubName = build.buildVariableResolver.resolve('GITHUB_NAME')
def displayName = build.buildVariableResolver.resolve('DISPLAY_NAME')

if (githubName && displayName) {
    job(displayName) {
        description("CI job generated by SEED for ${githubName}")

        properties {
            githubProjectUrl("https://github.com/${githubName}")
        }

        scm {
            git {
                remote {
                    url("https://github.com/${githubName}.git")
                }
                branches('*/main')
            }
        }

        triggers {
            scm('* * * * *')
        }

        wrappers {
            preBuildCleanup()
        }

        steps {
            shell('make fclean')
            shell('make')
            shell('make tests_run')
            shell('make clean')
        }
    }
}

